<a href="https://colab.research.google.com/github/godwins3/ml-playground/blob/main/numpy/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array(42) #0 D Arrays
print(arr)

42


In [ ]:
arr = np.array([1, 2, 3, 4, 5]) # 1D Array

print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2D Array

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3D Array

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr = np.array([23, 24, 25, 26])
print(arr[:3])

[23 24 25]


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 1])

2


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
a3 = a[:, np.newaxis]
a3.shape

(6, 1)

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
sorted_array = sorted(array, reverse=True)
print(sorted_array)

[9, 6, 5, 5, 4, 3, 2, 1, 1]


In [ ]:
a = np.array(([1, 2, 3, 4], [3, 5, 6, 7]))
b = np.array(([5, 6, 7, 8], [2, 1, 4, 8]))

In [ ]:
np.concatenate((a, b), axis=0)

array([[1, 2, 3, 4],
       [3, 5, 6, 7],
       [5, 6, 7, 8],
       [2, 1, 4, 8]])

In [ ]:
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [3, 5, 6, 7, 2, 1, 4, 8]])

In [ ]:
a = np.array(([[1, 2, 3, 4], [3, 5, 6, 7]], [[5, 6, 7, 8], [2, 1, 4, 8]]))
b = np.array(([[5, 6, 7, 8], [2, 1, 4, 8]], [[1, 2, 3, 4], [3, 5, 6, 7]]))

In [ ]:
np.concatenate((a, b), axis=0)

array([[[1, 2, 3, 4],
        [3, 5, 6, 7]],

       [[9, 0, 7, 8],
        [8, 7, 4, 8]],

       [[5, 6, 7, 8],
        [2, 1, 4, 8]],

       [[1, 2, 3, 4],
        [3, 5, 6, 7]]])

In [ ]:
a = np.array(([[1, 2, 3, 4], [3, 5, 6, 7]], [[9, 0, 7, 8], [8, 7, 4, 8]]))
b = np.array(([[5, 6, 7, 8], [2, 1, 4, 8]], [[1, 2, 3, 4], [3, 5, 6, 7]]))

In [ ]:
np.concatenate((a, b), axis=-1)

array([[[1, 2, 3, 4, 5, 6, 7, 8],
        [3, 5, 6, 7, 2, 1, 4, 8]],

       [[9, 0, 7, 8, 1, 2, 3, 4],
        [8, 7, 4, 8, 3, 5, 6, 7]]])

In [ ]:
lt = np.random.default_rng(1)
a = np.floor(10 * lt.random((2, 2)))
print(a)

[[5. 9.]
 [1. 9.]]


In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


Stacking arrays

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

stacked_array = np.vstack((array1, array2)) #vertical stacking  #Concatenates arrays along the first axis (rows)....requires arrays with same no of columns
print(stacked_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

stacked_array = np.hstack((array1, array2)) #horizontal stacking   #Concatenates arrays along the second axis (columns)....requires arrays with same no of rows
print(stacked_array)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

stacked_array = np.dstack((array1, array2)) #depth wise stacking
print(stacked_array)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Slicing

In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])

# Extract elements from index 1 to 4 (exclusive)
sliced_arr = arr[1:-1]
print(sliced_arr)

[1 2 3 4]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Extract the first row
sliced_arr = arr[1, -2:]
print(sliced_arr)

[5 6]


In [ ]:
arr = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                [[7, 8, 9],
                 [10, 11, 12]]])

# Extract the first slice (2D array)
sliced_arr = arr[0, 1, 0:2]
print(sliced_arr)

[4 5]


In [ ]:
#array[start:stop:step]
#start: The index of the first element to include.
#stop: The index of the first element to exclude.
#step: The number of elements to skip between elements.

In [ ]:
arr = np.array([7, 4, 1, 2, 3, 6, 5, 0, 7, 9, 10, 11])
arr2 = arr[1:8:]
print(arr2)

[4 1 2 3 6 5 0]


In [ ]:
array = np.array([1, 2, 3])
scalar = 2

result = array + scalar
print(result)

[3 4 5]


In [ ]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([7, 8, 9])

result = array1 + array2
print(result)

[[ 8 10 12]
 [11 13 15]]


In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([[7],
                   [8],
                   [9]])


result = np.dot(matrix, vector)
print(result)

[[ 50]
 [122]]


In [ ]:
x = np.array([0, np.pi/2, np.pi])
print(np.sin(x))

# Exponential and logarithmic functions
x = np.array([1, 100, 1000])
print(np.exp(x))
print(np.log10(x))

# Statistical functions
x = np.array([1, 2, 3, 4, 5])
print(np.mean(x))
print(np.std(x))

# Linear algebra functions
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))
print(np.linalg.inv(A))